# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FieldMeasurement.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 70, 711, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 4, 1, 1)
        self.time_step = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.time_step.setMaxLength(15)
        self.time_step.setObjectName("time_step")
        self.gridLayout.addWidget(self.time_step, 0, 5, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.length_step = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.length_step.setMaxLength(15)
        self.length_step.setObjectName("length_step")
        self.gridLayout.addWidget(self.length_step, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.temperature = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.temperature.setReadOnly(False)
        self.temperature.setObjectName("temperature")
        self.gridLayout.addWidget(self.temperature, 1, 3, 1, 1)
        self.humidity = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.humidity.setReadOnly(False)
        self.humidity.setObjectName("humidity")
        self.gridLayout.addWidget(self.humidity, 1, 5, 1, 1)
        self.total_length = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.total_length.setMaxLength(15)
        self.total_length.setObjectName("total_length")
        self.gridLayout.addWidget(self.total_length, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.frequency = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.frequency.setObjectName("frequency")
        self.gridLayout.addWidget(self.frequency, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 2, 1, 1)
        self.actual_frequency = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.actual_frequency.setReadOnly(True)
        self.actual_frequency.setObjectName("actual_frequency")
        self.gridLayout.addWidget(self.actual_frequency, 2, 3, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.temp_mea_once = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.temp_mea_once.setObjectName("temp_mea_once")
        self.gridLayout_2.addWidget(self.temp_mea_once, 1, 1, 1, 1)
        self.temp_typein = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.temp_typein.setObjectName("temp_typein")
        self.gridLayout_2.addWidget(self.temp_typein, 1, 3, 1, 1)
        self.temp_mea_more = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.temp_mea_more.setObjectName("temp_mea_more")
        self.gridLayout_2.addWidget(self.temp_mea_more, 1, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(190, 20, 411, 41))
        self.label_4.setObjectName("label_4")
        self.graphicsView = PlotWidget(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(30, 250, 441, 291))
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(540, 260, 191, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.start_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.start_button.setObjectName("start_button")
        self.verticalLayout.addWidget(self.start_button)
        self.stop_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.stop_button.setObjectName("stop_button")
        self.verticalLayout.addWidget(self.stop_button)
        self.run_information = QtWidgets.QTextBrowser(self.centralwidget)
        self.run_information.setGeometry(QtCore.QRect(510, 380, 251, 151))
        self.run_information.setObjectName("run_information")
        self.measurement_stratety = QtWidgets.QComboBox(self.centralwidget)
        self.measurement_stratety.setGeometry(QtCore.QRect(40, 220, 111, 22))
        self.measurement_stratety.setObjectName("measurement_stratety")
        self.measurement_stratety.addItem("")
        self.measurement_stratety.addItem("")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(270, 220, 71, 16))
        self.label_10.setObjectName("label_10")
        self.save_directory = QtWidgets.QTextBrowser(self.centralwidget)
        self.save_directory.setGeometry(QtCore.QRect(350, 220, 321, 21))
        self.save_directory.setObjectName("save_directory")
        self.change_directory = QtWidgets.QPushButton(self.centralwidget)
        self.change_directory.setGeometry(QtCore.QRect(670, 220, 75, 23))
        self.change_directory.setObjectName("change_directory")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menu)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.auto_find_com = QtWidgets.QAction(MainWindow)
        self.auto_find_com.setObjectName("auto_find_com")
        self.actionCOM6 = QtWidgets.QAction(MainWindow)
        self.actionCOM6.setObjectName("actionCOM6")
        self.actionCOM7 = QtWidgets.QAction(MainWindow)
        self.actionCOM7.setObjectName("actionCOM7")
        self.actionCOM5 = QtWidgets.QAction(MainWindow)
        self.actionCOM5.setObjectName("actionCOM5")
        self.actionCOM4 = QtWidgets.QAction(MainWindow)
        self.actionCOM4.setObjectName("actionCOM4")
        self.setting_port = QtWidgets.QAction(MainWindow)
        self.setting_port.setObjectName("setting_port")
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menu_2.addAction(self.auto_find_com)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.setting_port)
        self.menu.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.actionQuit.triggered.connect(MainWindow.close)
        self.temp_mea_once.clicked.connect(self.temperature.hide)
        self.temp_mea_once.clicked.connect(self.humidity.hide)
        self.temp_typein.clicked.connect(self.temperature.show)
        self.temp_typein.clicked.connect(self.humidity.show)
        self.temp_mea_more.clicked.connect(self.temperature.hide)
        self.temp_mea_more.clicked.connect(self.humidity.hide)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "谐振腔场分布测量程序"))
        self.label_5.setText(_translate("MainWindow", "温湿度数据"))
        self.label_3.setText(_translate("MainWindow", "等待时间(s)"))
        self.label_6.setText(_translate("MainWindow", "温度(摄氏度)"))
        self.label_2.setText(_translate("MainWindow", "测量步长(mm)"))
        self.label.setText(_translate("MainWindow", "腔体长度(mm)"))
        self.label_7.setText(_translate("MainWindow", "湿度(%)"))
        self.label_8.setText(_translate("MainWindow", "真空频率(MHz)"))
        self.label_9.setText(_translate("MainWindow", "腔体频率(MHz)"))
        self.temp_mea_once.setText(_translate("MainWindow", "单次测量"))
        self.temp_typein.setText(_translate("MainWindow", "手动输入"))
        self.temp_mea_more.setText(_translate("MainWindow", "多次测量"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">谐振腔场分布测量程序 beta1.0</span></p></body></html>"))
        self.start_button.setText(_translate("MainWindow", "开始"))
        self.stop_button.setText(_translate("MainWindow", "停止"))
        self.measurement_stratety.setItemText(0, _translate("MainWindow", "轴向场分布测量"))
        self.measurement_stratety.setItemText(1, _translate("MainWindow", "未完成"))
        self.label_10.setText(_translate("MainWindow", "数据保存路径"))
        self.change_directory.setText(_translate("MainWindow", "重新选择"))
        self.menuFile.setTitle(_translate("MainWindow", "文件"))
        self.menuHelp.setTitle(_translate("MainWindow", "帮助"))
        self.menu.setTitle(_translate("MainWindow", "选项"))
        self.menu_2.setTitle(_translate("MainWindow", "串口设置"))
        self.actionAbout.setText(_translate("MainWindow", "关于"))
        self.actionAbout.setShortcut(_translate("MainWindow", "Ctrl+H"))
        self.actionQuit.setText(_translate("MainWindow", "退出"))
        self.actionQuit.setIconText(_translate("MainWindow", "退出"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.auto_find_com.setText(_translate("MainWindow", "default"))
        self.actionCOM6.setText(_translate("MainWindow", "COM6"))
        self.actionCOM7.setText(_translate("MainWindow", "更多设置"))
        self.actionCOM5.setText(_translate("MainWindow", "COM5"))
        self.actionCOM4.setText(_translate("MainWindow", "COM4"))
        self.setting_port.setText(_translate("MainWindow", "更多设置"))

from pyqtgraph import PlotWidget
